### ISSUE TITLE
Improve annotation UI to avoid errorneous use

### ISSUE THREAD

**Issue by mikkohei13** [luomus/laji#615]
The most common error is that expert annotators observation as "erroneous X", when they are meaning it's either "confirmed X", or "probably X". We currently don't have option to change identification without assigning a quality level (verified, uncertain or erroneous).

We have drafted several options how the UI could be improved. Mikko has drafts on Figma, but they cannot be shared anymore.

We could do e.g.
 
- Minor adjustments to wording and arrangement
- Previewing or showing the outcome of the annotation
- Making a wizard-like UI that guides through the options

### Todo:

- [x] Decide if experts should be able to change identification without setting quality level
   - What would this need? New tag? Changes in ETL?
- [x] Make a design
- [x] Implement
- [x] Communicate to expert annotators

**Comment by mikkohei13** [comment]
The most common problem:

- observation is identified as species A, but has a photo of species B
- expert wants to say it's B
- expert annotates it as "erroneous B", when they should annotate it as "verified A"

**Comment by mikkohei13** [comment]
Use case for neutral annotation:

- Observer submits an observation as taxon A
- Someone questions the identification
- Observer says it's actually taxon B, but for some reason cannot correct the observation
- Annotator wants to change the taxon to B, without verifying it

**Comment by mikkohei13** [comment]
Specs:

- [ ] Move taxon field above tags. (see image)
- [ ] Move Ohje-button to the annotation box.
- [ ] Add shortcut buttons for confirming the identification (see image.)
      - Pressing this should add confirmed tag with current taxon
- [ ] If user add erroneous-tag and tries to save the annotation, display an alert. Specs below. 

![Image](https://github.com/user-attachments/assets/be6f95db-5b71-48ac-a302-94c0806e48c3)

### Alert

If user adds an annotation with tag "erroneous", and submits the annotation, show an additional confirmation dialogue/modal:

"Are you sure you want to set taxon { taxon name } as erroneous?" Yes | No

- If user clicks yes -> save the annotation.
- If user clicks no -> don't save the annotation, return the user to the annotation screen.

(Reason for the change: most erroneous-annotations should actually be confirmed-annotations.)

Translations:

    FI: Oletko varma, että haluat merkitä taksonin { taxon name } virheelliseksi?
    SE: Är du säker på att du vill markera taxon { taxon name } som felaktig?

**Comment by MLumme** [comment]
@mikkohei13 should the Shortcuts-button also be moved to the annotation box with the Ohje-button?

**Comment by mikkohei13** [comment]
Only Ohje. (I presume people rarely use shortcuts anyway, but we have no hard data about this.)

**Comment by MLumme** [comment]
Okay, and while moving Ohje I realized Shortcuts would've been a non-trivial task anyways.

**Comment by MLumme** [comment]
Testable here https://615.dev.laji.fi/observation/list

**Comment by mikkohei13** [comment]
Tested with Firefox, all works. Cannot test with other browsers while testing laji-auth is not working.

**Comment by mikkohei13** [comment]
Tested with Chrome 131 as well.
